CREATE DATABASE taskmanagement
  WITH
  OWNER = postgres
  ENCODING = 'UTF8'
  LC_COLLATE = 'English_United States.1252'
  LC_CTYPE = 'English_United States.1252'
  TABLESPACE = pg_default
  CONNECTION LIMIT = -1;

CREATE TABLE "public"."task" (
  "id" int4 NOT NULL GENERATED BY DEFAULT AS IDENTITY (
    INCREMENT 1
    MINVALUE  1
    MAXVALUE  2147483647
    START     1
  ),
  "title"       varchar     COLLATE "pg_catalog"."default",
  "description" varchar     COLLATE "pg_catalog"."default",
  "status"      varchar     COLLATE "pg_catalog"."default",
  CONSTRAINT    "task_pkey" PRIMARY KEY ("id")
);

ALTER TABLE "public"."task"
  OWNER TO "postgres";

INSERT INTO "task" (
  "id",
  "title",
  "description",
  "status"
)
VALUES (
  1,
  'title1',
  'description1',
  'OPEN'
);

CREATE TABLE "public"."user" (
  "id" int4 NOT NULL GENERATED BY DEFAULT AS IDENTITY (
    INCREMENT 1
    MINVALUE  1
    MAXVALUE  2147483647
    START     1
  ),
  "username" varchar     COLLATE "pg_catalog"."default",
  "password" varchar     COLLATE "pg_catalog"."default",
  CONSTRAINT "user_pkey" PRIMARY KEY ("id")
);

ALTER TABLE "public"."user"
    OWNER TO "postgres";


INSERT INTO "user" (
  "id",
  "username",
  "password"
)
VALUES (
  1,
  'User1',
  'passwordstring'
);
